#!/usr/bin/env python3

from zxv.reddit import ActivityDb
import argparse
import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np

def main():
    parser = argparse.ArgumentParser(
        prog="posts_per_hour",
        description="Plots posts per hour for a subreddit over a time range"
    )
    parser.add_argument("start_date", type=str)
    parser.add_argument("end_date", type=str)
    parser.add_argument("subreddit", nargs="+", type=str, help="Subreddit to fetch activity for")

    args = parser.parse_args()

    df_by_subreddit = {}
    with ActivityDb("activity.db") as db:
        for subreddit in args.subreddit:
            df = db.subreddit_posts_per_hour(subreddit, args.start_date, args.end_date)
            sma = df["count"].rolling(72).mean()
            df = df.join(sma, rsuffix="_sma")
            df_by_subreddit[subreddit] = df

    plt.figure(figsize=(10, 5))
    plt.ylabel("Posts per hour daily SMA")
    plt.xlabel("Date")
    ax = plt.gca()
    ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax.xaxis.get_major_locator()))
    for (subreddit, df) in df_by_subreddit.items():
        plt.plot(df["tm"], df["count_sma"], label=subreddit)
    plt.legend()
    plt.show()

if __name__ == "__main__":
    import sys
    sys.exit(main())
